### PR TITLE
test implementation of ubizara the bartender. 

### PR DESCRIPTION
**Pull request by BaldSavant**
Added/changed tracery syntax in various files and created a new generator for this character. Let me know if any part of this is done wildly wrong or whatever!

### CODE REVIEW

**Comment by lazerwalker** [comment]
Looks like the linter is failing with some simple whitespace issues -- can you try running `npm run lint-fix` in the project directory, and pushing those changes?

**Comment by lazerwalker** [comment]
(You can click the "details" button of the check at the bottom of this page, or go here: https://github.com/Roguelike-Celebration/azure-mud/runs/8120292578?check_suite_focus=true. Basically, you should be using spaces instead of tabs)

**Comment by BaldSavant** [comment]
I thought I was using spaces... but regardless, I have no idea how to use
that lint-fix command. Do you have a quick walkthrough you can link me to?
or describe to me?
___________________________________________________________________________

- Nathan Savant - My Blog <http://baldsavant.blogspot.com> - Portfolio Page
<http://www.nathansavant.com>

**Comment by lazerwalker** [comment]
If you already have a working command-line environment (which I'd imagine you do if you're able to run the local server), literally all you should need to do is run the command `npm run lint-fix` from the command-line and it should fix things.

If you don't have the project set up to run on the CLI: Download [Node.js](https://nodejs.org/en/). In the project directory, run `npm install`, and then `npm run lint-fix`.

Feel free to ping on Discord if you're having issues with that, might be faster than here

**Pull request merged**
